### PR TITLE
final commit

### PR DESCRIPTION
**Pull request by SaravShah**

### CODE REVIEW

**Comment by SaravShah** [comment]
Emmanuel: 
@mechamanny

**Comment by mechamanny** [comment]
Did you want me to review this one change?

**Comment by SaravShah** [comment]
Hi Emmanuel,

I think I meant to tag you on the Style.css but, the website already got
code reviewed by someone else. So sorry about that!

Thanks,
Sarav

**Comment by mechamanny** [comment]
Awesome, just checking in. =)

**Pull request merged**
